#!/usr/bin/env python3
"""Build per-PAR dossier CSVs.

Emits 13 CSVs to the chosen output directory:
  03_tm_domain_rrcs__parX__tm_interaction_matrix.csv             (×4)
  04_residue_wise_rrcs__parX__residues_ranked_by_signed_sum.csv  (×4)
  04_residue_wise_rrcs__parX__residues_ranked_by_max_delta.csv   (×4)
  04_residue_wise_rrcs___all_pars_cross_par_residue_comparison.csv (×1)

The residue metrics share their definition with the per-receptor website
(`gpcr_report_helpers._compute_residue_metrics`), so a residue's
`active_minus_inactive` here matches what the report page displays.

Usage:
    python scripts/build_par_dossier_csvs.py \
        --output-dir output_par2_preview/dossier/

    # subset of PARs (default: all four)
    python scripts/build_par_dossier_csvs.py --pars par2
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# Make the GPCompaReports_v2 package importable regardless of CWD.
HERE = Path(__file__).resolve().parent
V2_ROOT = HERE.parent
PROJECT_ROOT = V2_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))

from GPCompaReports_v2.analysis.data_loader import GPCRDataStore  # noqa: E402
from GPCompaReports_v2.website.page_generators.gpcr_report_helpers import (  # noqa: E402
    TM_HELICES,
    _compute_residue_metrics,
)

PAR_TO_GPCR_ID = {
    'par1': 'par1_human',
    'par2': 'par2_human',
    'par3': 'par3_human',
    'par4': 'par4_human',
}

TODAY = dt.date.today().isoformat()


def _write_with_header(df: pd.DataFrame, path: Path, header_lines: list[str], **to_csv_kwargs):
    """Prepend `# ...` comment lines, then df.to_csv()."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as fh:
        for line in header_lines:
            fh.write(line if line.startswith('#') else f'# {line}')
            fh.write('\n')
        df.to_csv(fh, **to_csv_kwargs)


def build_tm_interaction_matrix(delta_df: pd.DataFrame, annot_map: dict) -> pd.DataFrame:
    """Per-receptor 7×7 mean |ΔRRCS| matrix at TM-TM interfaces.

    Mirrors `analysis.tm_domain_analysis.compute_domain_interactions` but
    restricted to a single receptor's pair-level deltas.
    """
    seg_idx = {s: i for i, s in enumerate(TM_HELICES)}
    n = len(TM_HELICES)
    sums = np.zeros((n, n))
    counts = np.zeros((n, n))

    for _, row in delta_df.iterrows():
        seg1 = annot_map.get(int(row['res1']), {}).get('protein_segment', '')
        seg2 = annot_map.get(int(row['res2']), {}).get('protein_segment', '')
        if seg1 not in seg_idx or seg2 not in seg_idx:
            continue
        i, j = seg_idx[seg1], seg_idx[seg2]
        v = abs(float(row['delta_rrcs']))
        sums[i, j] += v
        counts[i, j] += 1
        if i != j:
            sums[j, i] += v
            counts[j, i] += 1

    with np.errstate(divide='ignore', invalid='ignore'):
        mean = np.where(counts > 0, sums / counts, 0.0)
    return pd.DataFrame(mean, index=TM_HELICES, columns=TM_HELICES)


def write_tm_matrix(par_key: str, gpcr_id: str, store: GPCRDataStore, output_dir: Path):
    delta_df = store.delta_data.get(gpcr_id, pd.DataFrame())
    annot_map = store.get_annotation_map(gpcr_id)
    matrix = build_tm_interaction_matrix(delta_df, annot_map)
    out = output_dir / f'03_tm_domain_rrcs__{par_key}__tm_interaction_matrix.csv'
    _write_with_header(
        matrix, out,
        header_lines=[
            f'03 TM-domain mean |ΔRRCS| at each TM-TM interface for {gpcr_id}.',
            "Each cell is mean(|delta_rrcs|) over all contact pairs whose endpoints "
            "lie in segments (TMi, TMj). Symmetric. Cells with no contact pairs are 0.",
            f'Generated by build_par_dossier_csvs.py on {TODAY}.',
        ],
        index=True,
    )
    print(f"  wrote {out.name}")


def write_residue_rankings(par_key: str, gpcr_id: str, store: GPCRDataStore,
                           output_dir: Path) -> pd.DataFrame:
    delta_df = store.delta_data.get(gpcr_id, pd.DataFrame())
    annot_map = store.get_annotation_map(gpcr_id)
    metrics = _compute_residue_metrics(delta_df, annot_map)
    cols = ['position', 'amino_acid', 'protein_segment', 'generic_number',
            'display_number', 'active_minus_inactive', 'max_abs_delta',
            'max_signed_delta', 'partner_at_max', 'n_contact_partners']
    metrics = metrics[cols]

    by_signed = metrics.sort_values('active_minus_inactive', ascending=False)
    out_signed = output_dir / f'04_residue_wise_rrcs__{par_key}__residues_ranked_by_signed_sum.csv'
    _write_with_header(
        by_signed, out_signed,
        header_lines=[
            f'04 Per-residue ΔRRCS for {gpcr_id}, ranked by active_minus_inactive (signed sum) descending.',
            "active_minus_inactive: ΔRRCS aggregated across all of a residue's contacts. "
            "Positive = net contact gain on activation.",
            'max_abs_delta: maximum |ΔRRCS| at this residue (the largest single contact change).',
            'max_signed_delta: signed ΔRRCS at the |Δ|-max contact (preserves sign).',
            'partner_at_max: partner residue at the |Δ|-max contact (one-letter AA + position).',
            f'Generated by build_par_dossier_csvs.py on {TODAY}.',
        ],
        index=False,
    )
    print(f"  wrote {out_signed.name}")

    by_max = metrics.sort_values('max_abs_delta', ascending=False)
    out_max = output_dir / f'04_residue_wise_rrcs__{par_key}__residues_ranked_by_max_delta.csv'
    _write_with_header(
        by_max, out_max,
        header_lines=[
            f'04 Per-residue ΔRRCS for {gpcr_id}, ranked by max_abs_delta (largest single contact change) descending.',
            'max_abs_delta: maximum |ΔRRCS| at this residue.',
            "active_minus_inactive: signed sum of ΔRRCS across all of a residue's contacts.",
            f'Generated by build_par_dossier_csvs.py on {TODAY}.',
        ],
        index=False,
    )
    print(f"  wrote {out_max.name}")
    return metrics


def write_cross_par_comparison(per_par_metrics: dict[str, pd.DataFrame], output_dir: Path):
    """One row per generic_number, columns wide across all four PARs."""
    pieces = []
    for par_key, df in per_par_metrics.items():
        upper = par_key.upper()
        sub = df.copy()
        # Prefer generic_number; fall back to display_number (GPCRdb identifier
        # for the position is stored in whichever field the annotation CSV used).
        gn = sub['generic_number'].astype(str)
        dn = sub['display_number'].astype(str)
        sub['generic_number'] = gn.where(gn.str.len() > 0, dn)
        sub = sub[sub['generic_number'].str.len() > 0]
        sub = sub.rename(columns={
            'amino_acid': f'AA_{upper}',
            'active_minus_inactive': f'signed_sum_{upper}',
            'max_abs_delta': f'max_delta_{upper}',
            'protein_segment': f'_seg_{par_key}',
        })
        pieces.append(sub[['generic_number', f'_seg_{par_key}',
                           f'AA_{upper}', f'signed_sum_{upper}', f'max_delta_{upper}']])

    if not pieces:
        return
    merged = pieces[0]
    for p in pieces[1:]:
        merged = merged.merge(p, on='generic_number', how='outer')

    seg_cols = [c for c in merged.columns if c.startswith('_seg_')]
    merged['protein_segment'] = (
        merged[seg_cols].bfill(axis=1).iloc[:, 0].fillna('')
    )
    merged = merged.drop(columns=seg_cols)

    signed_cols = [c for c in merged.columns if c.startswith('signed_sum_')]
    merged['_rank'] = merged[signed_cols].abs().max(axis=1).fillna(-1)
    merged = merged.sort_values('_rank', ascending=False).drop(columns='_rank')

    ordered = ['generic_number', 'protein_segment']
    for upper in ['PAR1', 'PAR2', 'PAR3', 'PAR4']:
        for prefix in ['AA_', 'signed_sum_', 'max_delta_']:
            col = f'{prefix}{upper}'
            if col in merged.columns:
                ordered.append(col)
    merged = merged[ordered]

    out = output_dir / '04_residue_wise_rrcs___all_pars_cross_par_residue_comparison.csv'
    _write_with_header(
        merged, out,
        header_lines=[
            'Cross-PAR residue comparison joined on GPCRdb generic_number.',
            'One row per generic-number position that appears in ≥1 PAR.',
            "AA_PARi: amino acid in PARi at that generic position. "
            "Blank = position has no contacts in PARi (or no annotation).",
            "signed_sum_PARi: active_minus_inactive (signed sum of ΔRRCS across contacts) for PARi.",
            "max_delta_PARi: max |ΔRRCS| at that residue in PARi.",
            'Sorted by max(|signed_sum_PAR*|) descending so cross-PAR hotspots float to the top.',
            f'Generated by build_par_dossier_csvs.py on {TODAY}.',
        ],
        index=False,
    )
    print(f"  wrote {out.name}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, required=True,
                        help='Directory to write the 13 CSVs into.')
    parser.add_argument('--pars', nargs='+', default=list(PAR_TO_GPCR_ID.keys()),
                        choices=list(PAR_TO_GPCR_ID.keys()),
                        help='Subset of PARs to process.')
    parser.add_argument('--batch-dir', type=str, default=None,
                        help='Batch analysis directory (default: auto).')
    parser.add_argument('--metadata', type=str, default=None,
                        help='Path to class_A_all.csv (default: auto).')
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading data store…")
    store = GPCRDataStore(batch_dir=args.batch_dir, metadata_csv=args.metadata)
    store.load_all()

    per_par_metrics: dict[str, pd.DataFrame] = {}
    for par_key in args.pars:
        gpcr_id = PAR_TO_GPCR_ID[par_key]
        if gpcr_id not in store.delta_data:
            print(f"  skip {par_key}: {gpcr_id} not in batch")
            continue
        print(f"\n[{par_key.upper()}] {gpcr_id}")
        write_tm_matrix(par_key, gpcr_id, store, args.output_dir)
        per_par_metrics[par_key] = write_residue_rankings(
            par_key, gpcr_id, store, args.output_dir,
        )

    if len(per_par_metrics) >= 2:
        print("\n[cross-PAR] joining residues across PARs by generic_number")
        write_cross_par_comparison(per_par_metrics, args.output_dir)
    else:
        print("\nSkipping cross-PAR file (need ≥2 PARs).")

    print(f"\nDone. Files in: {args.output_dir}")


if __name__ == '__main__':
    main()
